const installChecklistTypes = {
  FETCH_APPROVED_INSTALLATIONS_LOADING: 'INSTALL_CHECKLIST/FETCH_APPROVED_INSTALLATIONS_LOADING',
  FETCH_APPROVED_INSTALLATIONS_SUCCESS: 'INSTALL_CHECKLIST/FETCH_APPROVED_INSTALLATIONS_SUCCESS',
  FETCH_APPROVED_INSTALLATIONS_FAILURE: 'INSTALL_CHECKLIST/FETCH_APPROVED_INSTALLATIONS_FAILURE',

  FETCH_INSTALLATION_DETAILS_LOADING: 'INSTALL_CHECKLIST/FETCH_INSTALLATION_DETAILS_LOADING',
  FETCH_INSTALLATION_DETAILS_SUCCESS: 'INSTALL_CHECKLIST/FETCH_INSTALLATION_DETAILS_SUCCESS',
  FETCH_INSTALLATION_DETAILS_FAILURE: 'INSTALL_CHECKLIST/FETCH_INSTALLATION_DETAILS_FAILURE',
  CLEAR_INSTALLATION_DETAILS: 'INSTALL_CHECKLIST/CLEAR_INSTALLATION_DETAILS',
};

export default installChecklistTypes;
