const overviewTypes = {
    GET_TOTAL_ENERGY_TOP_CARD_LOADING: 'TOTAL_ENERGY_CARD_LOADING',
    GET_TOTAL_ENERGY_TOP_CARD_SUCCESS: 'TOTAL_ENERGY_CARD_SUCCESS',

    GET_CARBON_EMISSION_TOP_CARD_LOADING: 'CARBON_EMISSION_CARD_LOADING',
    GET_CARBON_EMISSION_TOP_CARD_SUCCESS: 'CARBON_EMISSION_CARD_SUCCESS',

    GET_TOTAL_ENERGY_BARCHART_LOADING: 'GET_TOTAL_ENERGY_BARCHART_LOADING',
    GET_TOTAL_ENERGY_BARCHART_SUCCESS: 'GET_TOTAL_ENERGY_BARCHART_SUCCESS',
}

export default overviewTypes;