const overviewTypes = {
    GET_TOTAL_ENERGY_TOP_CARD_LOADING: 'TOTAL_ENERGY_CARD_LOADING',
    GET_TOTAL_ENERGY_TOP_CARD_SUCCESS: 'TOTAL_ENERGY_CARD_SUCCESS',

    GET_TOTAL_ENERGY_BARCHART_LOADING: 'GET_TOTAL_ENERGY_BARCHART_LOADING',
    GET_TOTAL_ENERGY_BARCHART_SUCCESS: 'GET_TOTAL_ENERGY_BARCHART_SUCCESS',

    GET_TOTAL_COST_BARCHART_LOADING: 'GET_TOTAL_COST_BARCHART_LOADING',
    GET_TOTAL_COST_BARCHART_SUCCESS: 'GET_TOTAL_COST_BARCHART_SUCCESS',

    GET_UTILITY_ENERGY_LOADING: 'GET_UTILITY_ENERGY_LOADING',
    GET_UTILITY_ENERGY_SUCCESS: 'GET_UTILITY_ENERGY_SUCCESS',

    GET_DIESEL_COST_LOADING: 'GET_DIESEL_COST_LOADING',
    GET_DIESEL_COST_SUCCESS: 'GET_DIESEL_COST_SUCCESS',

    GET_DIESEL_LITRES_LOADING: 'GET_DIESEL_LITRES_LOADING',
    GET_DIESEL_LITRES_SUCCESS: 'GET_DIESEL_LITRES_SUCCESS',

    GET_KEY_METRICS_LOADING: 'GET_KEY_METRICS_LOADING',
    GET_KEY_METRICS_SUCCESS: 'GET_KEY_METRICS_SUCCESS',
}

export default overviewTypes;