const clientUserTypes = {
    ADD_CLIENT_USER_LOADING: 'ADD_CLIENT_USER_LOADING',
    ADD_CLIENT_USER_SUCCESS: 'ADD_CLIENT_USER_SUCCESS',

    GET_CLIENT_USER_LOADING: 'GET_CLIENT_USER_LOADING',
    GET_CLIENT_USER_SUCCESS: 'GET_CLIENT_USER_SUCCESS',
    
    EDIT_CLIENT_USER_LOADING: 'EDIT_CLIENT_USER_LOADING',
    EDIT_CLIENT_USER_SUCCESS: 'EDIT_CLIENT_USER_SUCCESS',

    DELETE_CLIENT_USER_LOADING: 'DELETE_CLIENT_USER_LOADING',
    DELETE_CLIENT_USER_SUCCESS: 'DELETE_CLIENT_USER_SUCCESS',
}

export default clientUserTypes;