const adminInvestorDirectoryTypes = {
  GET_ADMIN_FINANCE_BY_INVESTOR_LOADING: "GET_ADMIN_FINANCE_BY_INVESTOR_LOADING",
  GET_ADMIN_FINANCE_BY_INVESTOR_SUCCESS: "GET_ADMIN_FINANCE_BY_INVESTOR_SUCCESS",
};

export default adminInvestorDirectoryTypes;
