const adminInvestorInvestmentTypes = {
  GET_ADMIN_INVESTOR_INVESTMENTS_LOADING: "GET_ADMIN_INVESTOR_INVESTMENTS_LOADING",
  GET_ADMIN_INVESTOR_INVESTMENTS_SUCCESS: "GET_ADMIN_INVESTOR_INVESTMENTS_SUCCESS",

  CREATE_ADMIN_INVESTOR_INVESTMENT_LOADING: "CREATE_ADMIN_INVESTOR_INVESTMENT_LOADING",
  CREATE_ADMIN_INVESTOR_INVESTMENT_SUCCESS: "CREATE_ADMIN_INVESTOR_INVESTMENT_SUCCESS",

  GET_ADMIN_INVESTOR_INVESTMENT_DETAIL_LOADING: "GET_ADMIN_INVESTOR_INVESTMENT_DETAIL_LOADING",
  GET_ADMIN_INVESTOR_INVESTMENT_DETAIL_SUCCESS: "GET_ADMIN_INVESTOR_INVESTMENT_DETAIL_SUCCESS",
  CLEAR_ADMIN_INVESTOR_INVESTMENT_DETAIL: "CLEAR_ADMIN_INVESTOR_INVESTMENT_DETAIL",

  DELETE_ADMIN_INVESTOR_INVESTMENT_LOADING: "DELETE_ADMIN_INVESTOR_INVESTMENT_LOADING",
  DELETE_ADMIN_INVESTOR_INVESTMENT_SUCCESS: "DELETE_ADMIN_INVESTOR_INVESTMENT_SUCCESS",
};

export default adminInvestorInvestmentTypes;
