const adminCustomerPaymentTypes = {
  GET_ADMIN_CUSTOMER_PAYMENTS_LOADING: "GET_ADMIN_CUSTOMER_PAYMENTS_LOADING",
  GET_ADMIN_CUSTOMER_PAYMENTS_SUCCESS: "GET_ADMIN_CUSTOMER_PAYMENTS_SUCCESS",

  CREATE_ADMIN_CUSTOMER_PAYMENT_LOADING: "CREATE_ADMIN_CUSTOMER_PAYMENT_LOADING",
  CREATE_ADMIN_CUSTOMER_PAYMENT_SUCCESS: "CREATE_ADMIN_CUSTOMER_PAYMENT_SUCCESS",

  GET_ADMIN_CUSTOMER_PAYMENT_DETAIL_LOADING: "GET_ADMIN_CUSTOMER_PAYMENT_DETAIL_LOADING",
  GET_ADMIN_CUSTOMER_PAYMENT_DETAIL_SUCCESS: "GET_ADMIN_CUSTOMER_PAYMENT_DETAIL_SUCCESS",
  CLEAR_ADMIN_CUSTOMER_PAYMENT_DETAIL: "CLEAR_ADMIN_CUSTOMER_PAYMENT_DETAIL",

  DELETE_ADMIN_CUSTOMER_PAYMENT_LOADING: "DELETE_ADMIN_CUSTOMER_PAYMENT_LOADING",
  DELETE_ADMIN_CUSTOMER_PAYMENT_SUCCESS: "DELETE_ADMIN_CUSTOMER_PAYMENT_SUCCESS",
};

export default adminCustomerPaymentTypes;
