const overviewTypes = {
    GET_ALL_TIME_ENERGY_CONSUMPTION_LOADING: 'GET_ALL_TIME_ENERGY_CONSUMPTION_LOADING',
    GET_ALL_TIME_energy_CONSUMPTION_SUCCESS: 'GET_ALL_TIME_ENERGY_CONSUMPTION_SUCCESS',

    GET_THIS_MONTH_ENERGY_CONSUMPTION_LOADING: 'GET_THIS_MONTH_ENERGY_CONSUMPTION_LOADING',
    GET_THIS_MONTH_energy_CONSUMPTION_SUCCESS: 'GET_THIS_MONTH_ENERGY_CONSUMPTION_SUCCESS',

    GET_LAST_MONTH_ENERGY_CONSUMPTION_LOADING: 'GET_LAST_MONTH_ENERGY_CONSUMPTION_LOADING',
    GET_LAST_MONTH_ENERGY_CONSUMPTION_SUCCESS: 'GET_LAST_MONTH_ENERGY_CONSUMPTION_SUCCESS',

    GET_AMOUNT_LOADING: 'GET_AMOUNT_LOADING',
    GET_AMOUNT_SUCCESS: 'GET_AMOUNT_SUCCESS',
    
    GET_DEVICES_LIST_LOADING: 'GET_DEVICES_LIST_LOADING',
    GET_DEVICES_LIST_SUCCESS: 'GET_DEVICES_LIST_SUCCESS',
}

export default overviewTypes;