const locationTypes = {
  ADD_LOCATION_LOADING: "ADD_LOCATION_LOADING",
  ADD_LOCATION_SUCCESS: "ADD_LOCATION_SUCCESS",
  
  GET_LOCATION_LOADING: "GET_LOCATION_LOADING",
  GET_LOCATION_SUCCESS: "GET_LOCATION_SUCCESS",

  EDIT_LOCATION_LOADING: "EDIT_LOCATION_LOADING",
  EDIT_LOCATION_SUCCESS: "EDIT_LOCATION_SUCCESS",

  ADD_REGION_LOADING: "ADD_REGION_LOADING",
  ADD_REGION_SUCCESS: "ADD_REGION_SUCCESS",

  GET_REGION_LOADING: "GET_REGION_LOADING",
  GET_REGION_SUCCESS: "GET_REGION_SUCCESS",

  EDIT_REGION_LOADING: "EDIT_REGION_LOADING",
  EDIT_REGION_SUCCESS: "EDIT_REGION_SUCCESS",

  DELETE_REGION_LOADING: "DELETE_REGION_LOADING",
  DELETE_REGION_SUCCESS: "DELETE_REGION_SUCCESS",
};

export default locationTypes;