const adminInvestorOverviewTypes = {
  GET_ADMIN_INVESTOR_OVERVIEW_LOADING: "GET_ADMIN_INVESTOR_OVERVIEW_LOADING",
  GET_ADMIN_INVESTOR_OVERVIEW_SUCCESS: "GET_ADMIN_INVESTOR_OVERVIEW_SUCCESS",
};

export default adminInvestorOverviewTypes;
