const dieselTypes = {
    GET_DIESEL_LOADING: 'GET_DIESEL_LOADING',
    GET_DIESEL_SUCCESS: 'GET_DIESEL_SUCCESS',

    GET_DIESEL_PROCUREMENT_LOADING: 'GET_DIESEL_PROCUREMENT_LOADING',
    GET_DIESEL_PROCUREMENT_SUCCESS: 'GET_DIESEL_PROCUREMENT_SUCCESS',

    GET_DIESEL_CONSUMPTION_LOADING: 'GET_DIESEL_CONSUMPTION_LOADING',
    GET_DIESEL_CONSUMPTION_SUCCESS: 'GET_DIESEL_CONSUMPTION_SUCCESS',
}

export default dieselTypes;