const solarTypes = {
  FETCH_SOLAR_STATIONS_LOADING: 'SOLAR/FETCH_SOLAR_STATIONS_LOADING',
  FETCH_SOLAR_STATIONS_SUCCESS: 'SOLAR/FETCH_SOLAR_STATIONS_SUCCESS',
  FETCH_SOLAR_STATIONS_FAILURE: 'SOLAR/FETCH_SOLAR_STATIONS_FAILURE',

  FETCH_SOLAR_BRANCHES_LOADING: 'SOLAR/FETCH_SOLAR_BRANCHES_LOADING',
  FETCH_SOLAR_BRANCHES_SUCCESS: 'SOLAR/FETCH_SOLAR_BRANCHES_SUCCESS',
  FETCH_SOLAR_BRANCHES_FAILURE: 'SOLAR/FETCH_SOLAR_BRANCHES_FAILURE',

  SEARCH_SOLAR_STATION_LOADING: 'SOLAR/SEARCH_SOLAR_STATION_LOADING',
  SEARCH_SOLAR_STATION_SUCCESS: 'SOLAR/SEARCH_SOLAR_STATION_SUCCESS',
  SEARCH_SOLAR_STATION_NOT_FOUND: 'SOLAR/SEARCH_SOLAR_STATION_NOT_FOUND',
  SEARCH_SOLAR_STATION_FAILURE: 'SOLAR/SEARCH_SOLAR_STATION_FAILURE',
  CLEAR_SOLAR_STATION_SEARCH: 'SOLAR/CLEAR_SOLAR_STATION_SEARCH',

  SAVE_SOLAR_STATION_LOADING: 'SOLAR/SAVE_SOLAR_STATION_LOADING',
  SAVE_SOLAR_STATION_SUCCESS: 'SOLAR/SAVE_SOLAR_STATION_SUCCESS',
  SAVE_SOLAR_STATION_FAILURE: 'SOLAR/SAVE_SOLAR_STATION_FAILURE',

  TOGGLE_SOLAR_STATION_STATUS_LOADING: 'SOLAR/TOGGLE_SOLAR_STATION_STATUS_LOADING',
  TOGGLE_SOLAR_STATION_STATUS_SUCCESS: 'SOLAR/TOGGLE_SOLAR_STATION_STATUS_SUCCESS',
  TOGGLE_SOLAR_STATION_STATUS_FAILURE: 'SOLAR/TOGGLE_SOLAR_STATION_STATUS_FAILURE',

  FETCH_SOLAR_STATION_DETAILS_LOADING: 'SOLAR/FETCH_SOLAR_STATION_DETAILS_LOADING',
  FETCH_SOLAR_STATION_DETAILS_REFRESHING: 'SOLAR/FETCH_SOLAR_STATION_DETAILS_REFRESHING',
  FETCH_SOLAR_STATION_DETAILS_SUCCESS: 'SOLAR/FETCH_SOLAR_STATION_DETAILS_SUCCESS',
  FETCH_SOLAR_STATION_DETAILS_FAILURE: 'SOLAR/FETCH_SOLAR_STATION_DETAILS_FAILURE',

  UPDATE_SOLAR_DEVICE_LOADING: 'SOLAR/UPDATE_SOLAR_DEVICE_LOADING',
  UPDATE_SOLAR_DEVICE_SUCCESS: 'SOLAR/UPDATE_SOLAR_DEVICE_SUCCESS',
  UPDATE_SOLAR_DEVICE_FAILURE: 'SOLAR/UPDATE_SOLAR_DEVICE_FAILURE',
};

export default solarTypes;

