const clientSolarTypes = {
  FETCH_CS_GENERATING_NOW_LOADING: 'CLIENT_SOLAR/FETCH_GENERATING_NOW_LOADING',
  FETCH_CS_GENERATING_NOW_SUCCESS: 'CLIENT_SOLAR/FETCH_GENERATING_NOW_SUCCESS',
  FETCH_CS_GENERATING_NOW_FAILURE: 'CLIENT_SOLAR/FETCH_GENERATING_NOW_FAILURE',

  FETCH_CS_TODAY_LOADING: 'CLIENT_SOLAR/FETCH_TODAY_LOADING',
  FETCH_CS_TODAY_SUCCESS: 'CLIENT_SOLAR/FETCH_TODAY_SUCCESS',
  FETCH_CS_TODAY_FAILURE: 'CLIENT_SOLAR/FETCH_TODAY_FAILURE',

  FETCH_CS_THIS_MONTH_LOADING: 'CLIENT_SOLAR/FETCH_THIS_MONTH_LOADING',
  FETCH_CS_THIS_MONTH_SUCCESS: 'CLIENT_SOLAR/FETCH_THIS_MONTH_SUCCESS',
  FETCH_CS_THIS_MONTH_FAILURE: 'CLIENT_SOLAR/FETCH_THIS_MONTH_FAILURE',

  FETCH_CS_LIFETIME_LOADING: 'CLIENT_SOLAR/FETCH_LIFETIME_LOADING',
  FETCH_CS_LIFETIME_SUCCESS: 'CLIENT_SOLAR/FETCH_LIFETIME_SUCCESS',
  FETCH_CS_LIFETIME_FAILURE: 'CLIENT_SOLAR/FETCH_LIFETIME_FAILURE',

  FETCH_CS_STATUS_COUNTS_LOADING: 'CLIENT_SOLAR/FETCH_STATUS_COUNTS_LOADING',
  FETCH_CS_STATUS_COUNTS_SUCCESS: 'CLIENT_SOLAR/FETCH_STATUS_COUNTS_SUCCESS',
  FETCH_CS_STATUS_COUNTS_FAILURE: 'CLIENT_SOLAR/FETCH_STATUS_COUNTS_FAILURE',

  FETCH_CS_BRANCHES_LOADING: 'CLIENT_SOLAR/FETCH_BRANCHES_LOADING',
  FETCH_CS_BRANCHES_SUCCESS: 'CLIENT_SOLAR/FETCH_BRANCHES_SUCCESS',
  FETCH_CS_BRANCHES_FAILURE: 'CLIENT_SOLAR/FETCH_BRANCHES_FAILURE',

  FETCH_CS_BRANCH_TREND_LOADING: 'CLIENT_SOLAR/FETCH_BRANCH_TREND_LOADING',
  FETCH_CS_BRANCH_TREND_SUCCESS: 'CLIENT_SOLAR/FETCH_BRANCH_TREND_SUCCESS',
  FETCH_CS_BRANCH_TREND_FAILURE: 'CLIENT_SOLAR/FETCH_BRANCH_TREND_FAILURE',

  TOGGLE_CS_FAVOURITE_LOADING: 'CLIENT_SOLAR/TOGGLE_FAVOURITE_LOADING',
  TOGGLE_CS_FAVOURITE_SUCCESS: 'CLIENT_SOLAR/TOGGLE_FAVOURITE_SUCCESS',
  TOGGLE_CS_FAVOURITE_FAILURE: 'CLIENT_SOLAR/TOGGLE_FAVOURITE_FAILURE',

  FETCH_CS_ALARMS_LOADING: 'CLIENT_SOLAR/FETCH_ALARMS_LOADING',
  FETCH_CS_ALARMS_SUCCESS: 'CLIENT_SOLAR/FETCH_ALARMS_SUCCESS',
  FETCH_CS_ALARMS_FAILURE: 'CLIENT_SOLAR/FETCH_ALARMS_FAILURE',

  ACK_CS_ALARM_LOADING: 'CLIENT_SOLAR/ACK_ALARM_LOADING',
  ACK_CS_ALARM_SUCCESS: 'CLIENT_SOLAR/ACK_ALARM_SUCCESS',
  ACK_CS_ALARM_FAILURE: 'CLIENT_SOLAR/ACK_ALARM_FAILURE',

  CS_FORCE_LOGIN_LOADING: 'CLIENT_SOLAR/FORCE_LOGIN_LOADING',
  CS_FORCE_LOGIN_SUCCESS: 'CLIENT_SOLAR/FORCE_LOGIN_SUCCESS',
  CS_FORCE_LOGIN_FAILURE: 'CLIENT_SOLAR/FORCE_LOGIN_FAILURE',
};

export default clientSolarTypes;
