const branchTypes = {
    GET_BRANCH_DETAILS_LOADING: "GET_BRANCH_DETAILS_LOADING",
    GET_BRANCH_DETAILS_SUCCESS: "GET_BRANCH_DETAILS_SUCCESS",
    GET_PERMITTED_BRANCHES_LOADING: "GET_PERMITTED_BRANCHES_LOADING",
    GET_PERMITTED_BRANCHES_SUCCESS: "GET_PERMITTED_BRANCHES_SUCCESS",
    GET_PERMITTED_BRANCHES_FAIL: "GET_PERMITTED_BRANCHES_FAIL",
    FORCE_LOGIN_BRANCH_LOADING: "FORCE_LOGIN_BRANCH_LOADING",
    FORCE_LOGIN_BRANCH_SUCCESS: "FORCE_LOGIN_BRANCH_SUCCESS",
    FORCE_LOGIN_BRANCH_FAIL: "FORCE_LOGIN_BRANCH_FAIL",
  };
  
  export default branchTypes;