const investorTypes = {
  INVESTOR_PORTFOLIO_OVERVIEW_LOADING: "INVESTOR_PORTFOLIO_OVERVIEW_LOADING",
  INVESTOR_PORTFOLIO_OVERVIEW_SUCCESS: "INVESTOR_PORTFOLIO_OVERVIEW_SUCCESS",
  INVESTOR_PORTFOLIO_OVERVIEW_FAIL: "INVESTOR_PORTFOLIO_OVERVIEW_FAIL",
  INVESTOR_PROJECTS_LOADING: "INVESTOR_PROJECTS_LOADING",
  INVESTOR_PROJECTS_SUCCESS: "INVESTOR_PROJECTS_SUCCESS",
  INVESTOR_PAYMENTS_LOADING: "INVESTOR_PAYMENTS_LOADING",
  INVESTOR_PAYMENTS_SUCCESS: "INVESTOR_PAYMENTS_SUCCESS",
  INVESTOR_ACCOUNT_KYC_LOADING: "INVESTOR_ACCOUNT_KYC_LOADING",
  INVESTOR_ACCOUNT_KYC_SUCCESS: "INVESTOR_ACCOUNT_KYC_SUCCESS",
  INVESTOR_TOTAL_DEPOSITED_SUCCESS: "INVESTOR_TOTAL_DEPOSITED_SUCCESS",
  INVESTOR_SUPPORT_TICKETS_LOADING: "INVESTOR_SUPPORT_TICKETS_LOADING",
  INVESTOR_SUPPORT_TICKETS_SUCCESS: "INVESTOR_SUPPORT_TICKETS_SUCCESS",
  INVESTOR_SUPPORT_TICKETS_FAIL: "INVESTOR_SUPPORT_TICKETS_FAIL",
  INVESTOR_SUPPORT_TICKET_DETAIL_LOADING: "INVESTOR_SUPPORT_TICKET_DETAIL_LOADING",
  INVESTOR_SUPPORT_TICKET_DETAIL_SUCCESS: "INVESTOR_SUPPORT_TICKET_DETAIL_SUCCESS",
  INVESTOR_SUPPORT_TICKET_DETAIL_CLEAR: "INVESTOR_SUPPORT_TICKET_DETAIL_CLEAR",
  INVESTOR_SUPPORT_TICKET_CREATE_LOADING: "INVESTOR_SUPPORT_TICKET_CREATE_LOADING",
};

export default investorTypes;
