const accessControlTypes = {
  ACCESS_CONTROL_LOADING: "ACCESS_CONTROL_LOADING",
  ACCESS_CONTROL_SUCCESS: "ACCESS_CONTROL_SUCCESS",
  ACCESS_CONTROL_FAIL: "ACCESS_CONTROL_FAIL",
};

export default accessControlTypes;

