const adminInvestorSupportTicketTypes = {
  GET_ADMIN_SUPPORT_TICKETS_LOADING: "GET_ADMIN_SUPPORT_TICKETS_LOADING",
  GET_ADMIN_SUPPORT_TICKETS_SUCCESS: "GET_ADMIN_SUPPORT_TICKETS_SUCCESS",

  GET_ADMIN_SUPPORT_TICKET_DETAIL_LOADING: "GET_ADMIN_SUPPORT_TICKET_DETAIL_LOADING",
  GET_ADMIN_SUPPORT_TICKET_DETAIL_SUCCESS: "GET_ADMIN_SUPPORT_TICKET_DETAIL_SUCCESS",
  CLEAR_ADMIN_SUPPORT_TICKET_DETAIL: "CLEAR_ADMIN_SUPPORT_TICKET_DETAIL",

  CREATE_ADMIN_SUPPORT_TICKET_RESPONSE_LOADING: "CREATE_ADMIN_SUPPORT_TICKET_RESPONSE_LOADING",
};

export default adminInvestorSupportTicketTypes;
