const adminInvestorProjectTypes = {
  GET_ADMIN_INVESTOR_PROJECTS_LOADING: "GET_ADMIN_INVESTOR_PROJECTS_LOADING",
  GET_ADMIN_INVESTOR_PROJECTS_SUCCESS: "GET_ADMIN_INVESTOR_PROJECTS_SUCCESS",

  CREATE_ADMIN_INVESTOR_PROJECT_LOADING: "CREATE_ADMIN_INVESTOR_PROJECT_LOADING",
  CREATE_ADMIN_INVESTOR_PROJECT_SUCCESS: "CREATE_ADMIN_INVESTOR_PROJECT_SUCCESS",

  GET_ADMIN_INVESTOR_PROJECT_DETAIL_LOADING: "GET_ADMIN_INVESTOR_PROJECT_DETAIL_LOADING",
  GET_ADMIN_INVESTOR_PROJECT_DETAIL_SUCCESS: "GET_ADMIN_INVESTOR_PROJECT_DETAIL_SUCCESS",
  CLEAR_ADMIN_INVESTOR_PROJECT_DETAIL: "CLEAR_ADMIN_INVESTOR_PROJECT_DETAIL",

  DELETE_ADMIN_INVESTOR_PROJECT_LOADING: "DELETE_ADMIN_INVESTOR_PROJECT_LOADING",
  DELETE_ADMIN_INVESTOR_PROJECT_SUCCESS: "DELETE_ADMIN_INVESTOR_PROJECT_SUCCESS",
};

export default adminInvestorProjectTypes;
