const adminInvestorPayoutTypes = {
  GET_ADMIN_INVESTOR_PAYOUTS_LOADING: "GET_ADMIN_INVESTOR_PAYOUTS_LOADING",
  GET_ADMIN_INVESTOR_PAYOUTS_SUCCESS: "GET_ADMIN_INVESTOR_PAYOUTS_SUCCESS",

  CREATE_ADMIN_INVESTOR_PAYOUT_LOADING: "CREATE_ADMIN_INVESTOR_PAYOUT_LOADING",
  CREATE_ADMIN_INVESTOR_PAYOUT_SUCCESS: "CREATE_ADMIN_INVESTOR_PAYOUT_SUCCESS",

  GET_ADMIN_INVESTOR_PAYOUT_DETAIL_LOADING: "GET_ADMIN_INVESTOR_PAYOUT_DETAIL_LOADING",
  GET_ADMIN_INVESTOR_PAYOUT_DETAIL_SUCCESS: "GET_ADMIN_INVESTOR_PAYOUT_DETAIL_SUCCESS",
  CLEAR_ADMIN_INVESTOR_PAYOUT_DETAIL: "CLEAR_ADMIN_INVESTOR_PAYOUT_DETAIL",

  DELETE_ADMIN_INVESTOR_PAYOUT_LOADING: "DELETE_ADMIN_INVESTOR_PAYOUT_LOADING",
  DELETE_ADMIN_INVESTOR_PAYOUT_SUCCESS: "DELETE_ADMIN_INVESTOR_PAYOUT_SUCCESS",

  UPDATE_ADMIN_INVESTOR_PAYOUT_LOADING: "UPDATE_ADMIN_INVESTOR_PAYOUT_LOADING",

  GET_ADMIN_INVESTOR_PAYMENT_SCHEDULES_LIST_LOADING: "GET_ADMIN_INVESTOR_PAYMENT_SCHEDULES_LIST_LOADING",
  GET_ADMIN_INVESTOR_PAYMENT_SCHEDULES_LIST_SUCCESS: "GET_ADMIN_INVESTOR_PAYMENT_SCHEDULES_LIST_SUCCESS",
};

export default adminInvestorPayoutTypes;
