const solarMgtTypes = {
  // Realtime Power KPI
  FETCH_REALTIME_POWER_LOADING: 'SOLAR_MGT/FETCH_REALTIME_POWER_LOADING',
  FETCH_REALTIME_POWER_SUCCESS: 'SOLAR_MGT/FETCH_REALTIME_POWER_SUCCESS',
  FETCH_REALTIME_POWER_FAILURE: 'SOLAR_MGT/FETCH_REALTIME_POWER_FAILURE',

  // Daily Production KPI
  FETCH_DAILY_PRODUCTION_LOADING: 'SOLAR_MGT/FETCH_DAILY_PRODUCTION_LOADING',
  FETCH_DAILY_PRODUCTION_SUCCESS: 'SOLAR_MGT/FETCH_DAILY_PRODUCTION_SUCCESS',
  FETCH_DAILY_PRODUCTION_FAILURE: 'SOLAR_MGT/FETCH_DAILY_PRODUCTION_FAILURE',

  // Monthly Production KPI
  FETCH_MONTHLY_PRODUCTION_LOADING: 'SOLAR_MGT/FETCH_MONTHLY_PRODUCTION_LOADING',
  FETCH_MONTHLY_PRODUCTION_SUCCESS: 'SOLAR_MGT/FETCH_MONTHLY_PRODUCTION_SUCCESS',
  FETCH_MONTHLY_PRODUCTION_FAILURE: 'SOLAR_MGT/FETCH_MONTHLY_PRODUCTION_FAILURE',

  // Total Production KPI
  FETCH_TOTAL_PRODUCTION_LOADING: 'SOLAR_MGT/FETCH_TOTAL_PRODUCTION_LOADING',
  FETCH_TOTAL_PRODUCTION_SUCCESS: 'SOLAR_MGT/FETCH_TOTAL_PRODUCTION_SUCCESS',
  FETCH_TOTAL_PRODUCTION_FAILURE: 'SOLAR_MGT/FETCH_TOTAL_PRODUCTION_FAILURE',

  // Status Counts
  FETCH_STATUS_COUNTS_LOADING: 'SOLAR_MGT/FETCH_STATUS_COUNTS_LOADING',
  FETCH_STATUS_COUNTS_SUCCESS: 'SOLAR_MGT/FETCH_STATUS_COUNTS_SUCCESS',
  FETCH_STATUS_COUNTS_FAILURE: 'SOLAR_MGT/FETCH_STATUS_COUNTS_FAILURE',

  // Plants list
  FETCH_SOLAR_PLANTS_LOADING: 'SOLAR_MGT/FETCH_SOLAR_PLANTS_LOADING',
  FETCH_SOLAR_PLANTS_SUCCESS: 'SOLAR_MGT/FETCH_SOLAR_PLANTS_SUCCESS',
  FETCH_SOLAR_PLANTS_FAILURE: 'SOLAR_MGT/FETCH_SOLAR_PLANTS_FAILURE',

  // Toggle favourite
  TOGGLE_FAVOURITE_LOADING: 'SOLAR_MGT/TOGGLE_FAVOURITE_LOADING',
  TOGGLE_FAVOURITE_SUCCESS: 'SOLAR_MGT/TOGGLE_FAVOURITE_SUCCESS',
  TOGGLE_FAVOURITE_FAILURE: 'SOLAR_MGT/TOGGLE_FAVOURITE_FAILURE',

  // Alarms list
  FETCH_ALARMS_LOADING: 'SOLAR_MGT/FETCH_ALARMS_LOADING',
  FETCH_ALARMS_SUCCESS: 'SOLAR_MGT/FETCH_ALARMS_SUCCESS',
  FETCH_ALARMS_FAILURE: 'SOLAR_MGT/FETCH_ALARMS_FAILURE',

  // Acknowledge alarm
  ACK_ALARM_LOADING: 'SOLAR_MGT/ACK_ALARM_LOADING',
  ACK_ALARM_SUCCESS: 'SOLAR_MGT/ACK_ALARM_SUCCESS',
  ACK_ALARM_FAILURE: 'SOLAR_MGT/ACK_ALARM_FAILURE',

  // Solar Clients
  FETCH_SOLAR_CLIENTS_LOADING: 'SOLAR_MGT/FETCH_SOLAR_CLIENTS_LOADING',
  FETCH_SOLAR_CLIENTS_SUCCESS: 'SOLAR_MGT/FETCH_SOLAR_CLIENTS_SUCCESS',
  FETCH_SOLAR_CLIENTS_FAILURE: 'SOLAR_MGT/FETCH_SOLAR_CLIENTS_FAILURE',
};

export default solarMgtTypes;
