const adminInvestorUserTypes = {
  GET_ADMIN_INVESTOR_USERS_LOADING: "GET_ADMIN_INVESTOR_USERS_LOADING",
  GET_ADMIN_INVESTOR_USERS_SUCCESS: "GET_ADMIN_INVESTOR_USERS_SUCCESS",

  CREATE_ADMIN_INVESTOR_USER_LOADING: "CREATE_ADMIN_INVESTOR_USER_LOADING",
  CREATE_ADMIN_INVESTOR_USER_SUCCESS: "CREATE_ADMIN_INVESTOR_USER_SUCCESS",

  GET_ADMIN_INVESTOR_USER_DETAIL_LOADING: "GET_ADMIN_INVESTOR_USER_DETAIL_LOADING",
  GET_ADMIN_INVESTOR_USER_DETAIL_SUCCESS: "GET_ADMIN_INVESTOR_USER_DETAIL_SUCCESS",
  CLEAR_ADMIN_INVESTOR_USER_DETAIL: "CLEAR_ADMIN_INVESTOR_USER_DETAIL",

  DELETE_ADMIN_INVESTOR_USER_LOADING: "DELETE_ADMIN_INVESTOR_USER_LOADING",
  DELETE_ADMIN_INVESTOR_USER_SUCCESS: "DELETE_ADMIN_INVESTOR_USER_SUCCESS",
};

export default adminInvestorUserTypes;
